version: '3'

services:
  php-fpm:
    container_name: test-php-fpm
    build:
      context: .docker/php
    volumes:
      - ./:/var/www/html
      - php_socket:/var/run/php
    networks:
      - net-test
    links:
      - mysql
    depends_on:
      - mysql
    env_file:
      - .env
  web:
    container_name: test-web
    build:
      context: .docker/nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - net-test
    links:
      - php-fpm
    env_file:
      - .env

  mysql:
    image: mysql:8
    container_name: test-mysql
    command: --default-authentication-plugin=mysql_native_password; mysqld --max_allowed_packet=64M
    ports:
      - 3309:3309
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_TCP_PORT=3309
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_DATABASE}
    networks:
      - net-test

volumes:
  php_socket:

networks:
  net-test:
    name: net-test
    driver: bridge